### ISSUE TITLE
Transfer-Encoding: Chunked

### ISSUE THREAD

**Issue by AlexGiovanentti** [lonelycode/tyk#106]
Is Transfer-Encoding: chunked supported?

We have streaming endpoints that require this feature.
We have successfully been able to proxy most of our endpoints with Tyk except the endpoints that depend on Transfer-Encoding: chunked.
With other API Gateway solutions we have evaluated and that feature nginx, setting proxy_buffering off; in nginx.conf has enable the feature.

Thank you for your time.

**Comment by lonelycode** [comment]
We haven't tested for it, might be a bug.
Tyk isn't nginx based, so it's something we'll need to investigate.






On Thu, Sep 10, 2015 at 10:20 PM -0700, "AlexGiovanentti" <notifications@github.com> wrote:












Is Transfer-Encoding: chunked supported?



We have streaming endpoints that require this feature.

We have successfully been able to proxy most of our endpoints with Tyk except the endpoints that depend on Transfer-Encoding: chunked.

With other nginx proxy solutions setting proxy_buffering off; in nginx.conf has enable the feature.



Thank you for your time.

**Comment by lonelycode** [comment]
Have you tried setting close_connections in the Tyk.conf file to false? 
This setting forces the proxy to close the upstream connection as soon as it gets a response.







On Thu, Sep 10, 2015 at 10:20 PM -0700, "AlexGiovanentti" <notifications@github.com> wrote:












Is Transfer-Encoding: chunked supported?



We have streaming endpoints that require this feature.

We have successfully been able to proxy most of our endpoints with Tyk except the endpoints that depend on Transfer-Encoding: chunked.

With other nginx proxy solutions setting proxy_buffering off; in nginx.conf has enable the feature.



Thank you for your time.

**Comment by lonelycode** [comment]
**Confirmed solution**: To enable processing of Transfer-Encoding: chunked, set the `close_connections` property in the `tyk.conf` file to `false` (or remove the line altogether).

Tyk aggressively closes TCP connections by default, to stop this from happening you can unset this option and Tyk will respect HTTP 1.1 convention to keep open TCP channels per client.

**Comment by AlexGiovanentti** [comment]
Would your proposed solution pass-through the chunks of data as they are received or wait till the end of the stream?

Case Study:
We have an endpoint that uses Transfer-Encoding: chunked; to continuously send chunks of data with updates on any changes to the price of a stock. The stream does not have a deterministic end. The expected api gateway behavior would be to pass through the chunks of data as they are received from the upstream server.

When visiting this endpoint through a browser like chrome the chunks of data are rendered as they are received.
When visiting this endpoint in the same manner but through the gateway the browser waits and eventually displays a 504 Gateway Time-out nginx/1.9.4.
We experience this before and after the proposed change to the tyk.conf property close_connections.

**Comment by lonelycode** [comment]
Ah I see, this solution might just cause the proxy to fill the buffer and then proxy back. The tests I ran were against the httpbin stream endpoint (which returns a chunked response). 
This will need further investigation, since we don't have an easily accessible streaming API to test against, unless you have a good example available to hand? :-)

**Comment by lonelycode** [comment]
Right, I think we can make this configurable - currently the default flush interval to write to the client is set to 0 so there is no periodic writes.
If we make this configurable then that should fix this problem.

**Comment by AlexGiovanentti** [comment]
I can provide a streaming endpoint. Would you have a public email I can send this information to?

**Comment by lonelycode** [comment]
Yup - martin@tyk.io

**Comment by lonelycode** [comment]
This has now been addressed in the master branch, will be in the next point release.

Enable streaming endpoints by setting a flush interval (in seconds) in your `tyk.conf` file:

    "http_server_options": {
        "flush_interval": 1
    }

**Comment by lonelycode** [comment]
This is now in an active release: https://github.com/lonelycode/tyk/releases/tag/v1.8.3.2

**Comment by AlexGiovanentti** [comment]
I deployed 1.8.3.2 and set the flush_interval setting: 1
however now when I hit a streaming endpoint through Tyk it spins for a little while and then alerts with the following error:
Chome: ERR_INCOMPLETE_CHUNKED_ENCODING
Fiddler: 210 Transfer-Encoding: Chunked response did not terminate with a proper zero-size chunk

Is there anything else I need to set or update besides the flush_interval setting?

**Comment by lonelycode** [comment]
You will need to set the close_connections flag too as otherwise the writer will send a close header which terminates after the first flush.
Let me know if that works...

**Comment by AlexGiovanentti** [comment]
I set close_connections to false and the issue still persists

**Comment by lonelycode** [comment]
You will need to set it to true. Can you share your Tyk.conf?





On Tue, Sep 22, 2015 at 6:02 AM -0700, "Alex Giovannetti" <notifications@github.com> wrote:












I set close_connections to false and the issue still persists

**Comment by AlexGiovanentti** [comment]
I reverted close_connections from false to true, same results.
I have also emailed you some test endpoints and their results

The following is the tyk.conf from the tyk_gateway docker container
```
{
    "listen_port": 8080,
    "secret": "352d20ee67be67f6340b4c0605b044b7",
    "template_path": "./templates",
    "tyk_js_path": "./js/tyk.js",
    "middleware_path": "./middleware",
    "use_db_app_configs": true,
    "app_path": "./apps/",
    "storage": {
        "type": "redis",
        "host": "redis",
        "port": 6379,
        "username": "",
        "password": "",
        "database": 0,
        "optimisation_max_idle": 100
    },
    "enable_analytics": true,
    "analytics_config": {
        "type": "mongo",
        "csv_dir": "/tmp",
        "mongo_url": "mongodb://mongo:27017/tyk_analytics",
        "mongo_db_name": "tyk_analytics",
        "mongo_collection": "tyk_analytics",
        "purge_delay": 10,
        "ignored_ips": []
    },
    "health_check": {
        "enable_health_checks": true,
        "health_check_value_timeouts": 60
    },
    "optimisations_use_async_session_write": true,
    "allow_master_keys": false,
    "policies": {
        "policy_source": "mongo",
        "policy_record_name": "tyk_policies"
    },
    "hash_keys": true,
    "close_connections": true,
    "http_server_options": {
        "flush_interval": 1
    }
}
```

**Comment by lonelycode** [comment]
My bad, close_connections needs to be false (duh), replied in haste.

Will reply directly to your email.

**Comment by AlexGiovanentti** [comment]
Hi Martin, got it working. Thank you for you time on this issue!

**Comment by johnjelinek** [comment]
@lonelycode: I've got:
```
  "close_connections": false,
  "http_server_options": {
    "flush_interval": 1
  }
```
in the `tyk.conf` and chunked streams don't seem to be working for me. How can I troubleshoot?

**Comment by johnjelinek** [comment]
nvm, I forgot to add `--compressed` to curl. My bad.
